### ISSUE TITLE
Automatically add the type info with serializing

### ISSUE THREAD

**Issue by leonsoft** [FasterXML/jackson-future-ideas#12]
The main idea is to add type info automatically anywhere the concrete instance's data type is not the same as the declared data type. In this case, everything is de/serialized automatically.  

The questions is desribed here in more detail:
[http://stackoverflow.com/questions/41086140/how-to-enable-automatic-typing-with-jackson-
serialization](http://stackoverflow.com/questions/41086140/how-to-enable-automatic-typing-with-jackson-serialization)

**Comment by cowtowncoder** [comment]
How would this work on deserialization? There is only instance type available during serialization, not deserialization.

**Comment by leonsoft** [comment]
since type info is present where necessary, you can create the instance during deserialization.

**Comment by leonsoft** [comment]
I'm quite sure this is feasible as I just noticed that json.net supports this feature.

**Comment by cowtowncoder** [comment]
@leonsoft You gotta be kidding me.
