### ISSUE TITLE
Annotation to ignore all properties except the ones specified

### ISSUE THREAD

**Issue by cen1** [FasterXML/jackson-future-ideas#15]
I've been googling around and on SO but couldn't really find anything similar. Basically a lot of times I want something like `@JsonIgnoreAllPopertiesExcept({"this_one", "and_this_one"})`, so the opposite of `@JsonIgnoreProperties`. In real world usage scenarios, more often than not it seems that I need to ignore almost all properties from the child entity except a few. If my child entity has 20 properties, I have to write 15 names in `@JsonIgnoreProperties` but with this new annotation I could just specify the ones I want and all others should be ignored. Hopefully that makes sense.

**Comment by cowtowncoder** [comment]
So, like this existing issue?

https://github.com/FasterXML/jackson-databind/issues/1296

If so, yes, I grok and like the idea. Was hoping to work on it for 2.9, but unfortunately seems unlikely there's time.

**Comment by cen1** [comment]
Yes, exactly like that. I'm glad the proposal already exists.

**Comment by cowtowncoder** [comment]
Ok thank you verifying. I agree it is a good idea.

**Comment by RahulKesharwani** [comment]
Hi, 

Is there any update on implementing the mentioned feature??

**Comment by cowtowncoder** [comment]
@RahulKesharwani as per earlier notes issue is:

https://github.com/FasterXML/jackson-databind/issues/1296

and if there are updates, whoever works on issue should add notes to issue. I am not aware of any progress.
