### ISSUE TITLE
Create `jackson-datatype-jdbc`?

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-future-ideas#2]
(from: https://github.com/FasterXML/jackson-databind/issues/717)
### Support conversion of JDBC ResultSet to JSON

This has come up on the list before
http://markmail.org/message/2jcqzbdcl2qvg7a2

but it'd be very handy to be able to convert a JDBC ResultSet to a JSON POJO using the Jackson ObjectMapper stuff, so folks could easily stream JDBC ResultSets as JSON/XML from JAXRS resources. Might be nice to have folks use Jackson and Brian's jDBI together etc.

Extra beer tokens, if Jackson could convert a ResultSet into a (lazy) List so that folks can use Guava/Java8/Scala/Groovy/Kotlin map/filter stuff on the result set beans first before rendering the JSON.

**Comment by danielmelogpi** [comment]
The result of this would be, like:
- query database with some injected jackson magic
- get a serialized resultset (String?)
?

**Comment by cowtowncoder** [comment]
No: the result would handlers (parser or deserializer), most likely for `ResultSet`, so that one would get a query result and ask Jackson to bind it to regular Java object(s) using name matching. I suspect this would be quite similar to `jackson-dataformat-csv` or `jackson-dataformat-properties` (both moved under `jackson-dataformats-text` for 2.9).

In fact, this probably should be modeled as data format instead of datatype, since data does not really exist at serialization. Here similarity to "properties" format handler (with input type of `Properties`) is closest.

**Comment by cowtowncoder** [comment]
No plans here; if anyone wants to pick it up may be reopened with preliminary plan/overview.
