### ISSUE TITLE
Support setting DeserializationFeature on specific class or field

### ISSUE THREAD

**Issue by liangde-chen** [FasterXML/jackson-future-ideas#29]
For example I want to enable     ACCEPT_FLOAT_AS_INT for specific field but not globally

**Comment by cowtowncoder** [comment]
I am open to specific additions of new `JsonFormat.Feature` settings: please feel free to file specific individual requests against `jackson-databind`. Will close this general request

**Comment by Anatoly4444** [comment]
@cowtowncoder could you add READ_UNKNOWN_ENUM_VALUES_AS_NULL to JsonFormat.Feature. Just don't want to make this feature for whole project

**Comment by cowtowncoder** [comment]
@Anatoly4444 Please file a new issue for `jackson-databind` (even if annotation change goes in `jackson-annotations`).
