### ISSUE TITLE
Configure recursion solving algorithm

### ISSUE THREAD

**Issue by Thiamath** [FasterXML/jackson-future-ideas#3]
Hi there!
Loving this lib!
BTW I'm hardly working with it in my job and found some troubles when serializing objects with crossing dependencies. My last headache is the User-Role-Group triad with many-to-many relations between them.
I've found that serializing algorithm in these cases are always "Depth first" (what in my case is killing me) so I thought that it would be great to be able to configure by annotations (best for me) or general configuration the use of "Depth first" or "Breadth first" algorithms to resolve recursion in addition with @JsonIdentityInfo which works like a charm.
Wadaya think?

**Comment by cowtowncoder** [comment]
@Thiamath I am not quite sure how this would work, regarding change, but if you want to try out an implementation for it, I could help with configuration part. But configurability seems like simple part, it is figuring out how serialization side would change that seems difficult. I have no objections to anyone's work, although I would like to understand problem being solved.
