### ISSUE TITLE
support booleans

### ISSUE THREAD

**Issue by mcandre** [FasterXML/jackson-future-ideas#4]

**Comment by cowtowncoder** [comment]
Huh?

**Comment by mcandre** [comment]
Have out of the box support for (de)serializing Java (bB)oolean values

**Comment by cowtowncoder** [comment]
That already exists.

**Comment by mcandre** [comment]
Which version of Jackson supports booleans?

**Comment by cowtowncoder** [comment]
@mcandre `bool`s and `Boolean`s have been supported from the very first version.

**Comment by khogeland** [comment]
Can we get JSON support soon, too?

**Comment by cowtowncoder** [comment]
@khogeland You may be thrilled to know that Jackson also supports JSON as is.

**Comment by mcandre** [comment]
lol

someone told me jackson didn't support booleans :P

**Comment by cowtowncoder** [comment]
@mcandre Ah ok. Rumors of non-support are greatly exaggerated. :)
