### ISSUE TITLE
Enabling XML > JSON > XML lossless conversion without static information (no POJO, transformation rules, ...)

### ISSUE THREAD

**Issue by MP-85** [FasterXML/jackson-future-ideas#42]
Hello,

we have the requirement to do an XML > JSON conversion that could be reverted (so, the resulting JSON should contain all information for going back to the original XML).

According to our requirements, the conversion must not rely on any a priori information (no POJO, transformation rules, ...).

This means that the conversion should keep the root element, namespaces, attributes and arrays.

Currently, for what seen Jackson is not supporting these requests (we have done some tests and the xml root element and namespaces are not preserved, only the first element of an array is converted, ...), so we have created an internal library that is able to do this kind of bidirectional lossless conversions, able to give in output an XML' (XML > JSON > XML') that is equivalent to the original one, without any a priori information.

Are you interested in integrating this features in Jackson?

**Comment by cowtowncoder** [comment]
Yes, I think this could be an interesting component... perhaps a new dataformat component, that could expose "XML as JSON", if that is feasible.

The biggest challenge is that of whether operation can fit nicely to Jackson extension points, however; if it can not use existing APIs, then it probably makes more sense as a standalone project/library.
I am not sure it would fit within existing  XML modules for example (but maybe it would? As separate mode)

One thing that would be helpful would be documentation on how conversion works: I assume it will use naming convention to produce "frankenJSON".

**Comment by cowtowncoder** [comment]
That API would not unfortunately really work with other components: it sounds more like stand-alone tool. That is fine of course and useful, but maybe it would make sense to release as a separate component of its own.

**Comment by MP-85** [comment]
Ok, thank you for the prompt reply!

**Comment by cowtowncoder** [comment]
One quick note: Jackson 2.12 included important improvements to handling of `JsonNode` for XML content: it now allows handling of repeated elements as "Arrays". This makes it more feasible to do XML -> JSON conversions, losslessly for some cases.

Other than that writing separate tools makes sense; not sure of an approach that would build as direct Jackson core extension.
