### ISSUE TITLE
Create git tags for releases

### ISSUE THREAD

**Issue by TheSnoozer** [FasterXML/jackson-future-ideas#44]
This is a rather small thing and would be related to the 'distribution' of the project, but I think any release should be tagged within git.

Benefits are clearly that one can compare versions more easily (including automated processes) and one could write release notes to specific versions (e.g. https://github.com/gradle/gradle/releases)

**Comment by cowtowncoder** [comment]
All releases are automatically tagged by Maven release plug-in aren't they? So I am not sure what else would be beneficial?

**Comment by TheSnoozer** [comment]
Ahh sorry...I just realized that dependabot (that attempted to autofix a recent CVE) was linking to https://github.com/FasterXML/jackson....that repo obviously doesn't contain any tags/releases, however https://github.com/FasterXML/jackson-databind/ does and is what I was suggesting.

Sorry for the confusion, all good.

**Comment by cowtowncoder** [comment]
Ah! Yes that makes more sense. Definitely would not want non-reproducible builds etc so better safe than sorry. Just wanted to make sure there wasn't something else missing!
