### ISSUE TITLE
Exceptionless ObjectMapper.writeValueAsString(Bytes)

### ISSUE THREAD

**Issue by buckelieg** [FasterXML/jackson-future-ideas#54]
Remove annoying JsonProcessingException (replace it with runtime exception) for mapper to be able efficiently used in functional programming style (lambda).

**Comment by cowtowncoder** [comment]
For Jackson 2.x this is not possible: it is possible to get a databinding exception during serialization -- not all failures are due to i/o.

But Jackson 3.x will change this exception to be unchecked:

https://github.com/FasterXML/jackson-databind/issues/2177

so that it need not be caught.
