### ISSUE TITLE
Mappings to two dimensional data structures

### ISSUE THREAD

**Issue by wbuchanan** [FasterXML/jackson-future-ideas#6]
It would be huge if there were an efficient way to map arbitrarily nested JSON structures into a two dimensional space.  An example of how it might work (that involves using R/C++) can be viewed in the [jsonlite](https://github.com/jeroenooms/jsonlite) repo.  While JSON support in RDBMS is getting better, it still isn't great in many analytic languages, so something like this would definitely make life way easier for a fair number of people.

**Comment by cowtowncoder** [comment]
I think I'd like to hear bit more to understand what the idea here is: I do not see much in way of documentation on jsonlite.

For what is worth there are two Jackson dataformat modules, CSV (https://github.com/FasterXML/jackson-dataformat-csv/) and Java Properties (https://github.com/FasterXML/jackson-dataformat-properties) which are somewhat related; CSV being two-dimensional format, and Properties as being mapped to flat key/value set using naming convention (dotted path).

**Comment by wbuchanan** [comment]
@cowtowncoder I've looked into both of those modules.  The properties would be great if the model of the JSON is known _a priori_ but is a bit less helpful when trying to handle arbitrary JSON efficiently and the CSV module mentions that it isn't that great for deeply nested JSON structures.  So here is a relatively common model of data in the education sector (granted again this is known _a priori_ and the challenge is handling arbitrary JSON):

```
school, student, school_year, grade, test_type, test_score
1, 1, 2015, 11, "reading", 275
1, 1, 2015, 11, "math", 325
1, 1, 2015, 11, "sat", 1950
1, 1, 2016, 12, "sat", 1975
1, 2, 2014, 7, "reading", 200
1, 2, 2014, 7, "math", 193
1, 2, 2015, 8, "reading", 215
1, 2, 2015, 8, "math", 197
```

It can be very literally translated to JSON:

```R
library(magrittr)
library(magrittr)

example <- list("school" = rep(1, 8),
	 "student" = c(rep(1, 4), rep(2, 4)),
	 "school_year" = c(rep(2015, 3), 2016, 2014, 2014, 2015, 2015),
	 "grade" = c(rep(11, 3), 12, 7, 7, 8, 8),
	 "test_type" = c("reading", "math", "sat", "sat", rep(c("reading", "math"), 2)), 
	 "test_score" = c(275, 325, 1950, 1975, 200, 193, 215, 197)) %>%
	 as.data.frame(stringsAsFactors = FALSE)

jsonlite::prettify(jsonlite::toJSON(example))

[
    {
        "school": 1,
        "student": 1,
        "school_year": 2015,
        "grade": 11,
        "test_type": "reading",
        "test_score": 275
    },
    {
        "school": 1,
        "student": 1,
        "school_year": 2015,
        "grade": 11,
        "test_type": "math",
        "test_score": 325
    },
    {
        "school": 1,
        "student": 1,
        "school_year": 2015,
        "grade": 11,
        "test_type": "sat",
        "test_score": 1950
    },
    {
        "school": 1,
        "student": 1,
        "school_year": 2016,
        "grade": 12,
        "test_type": "sat",
        "test_score": 1975
    },
    {
        "school": 1,
        "student": 2,
        "school_year": 2014,
        "grade": 7,
        "test_type": "reading",
        "test_score": 200
    },
    {
        "school": 1,
        "student": 2,
        "school_year": 2014,
        "grade": 7,
        "test_type": "math",
        "test_score": 193
    },
    {
        "school": 1,
        "student": 2,
        "school_year": 2015,
        "grade": 8,
        "test_type": "reading",
        "test_score": 215
    },
    {
        "school": 1,
        "student": 2,
        "school_year": 2015,
        "grade": 8,
        "test_type": "math",
        "test_score": 197
    }
]
```

But that is fairly inefficient in terms of data storage.  It could also be represented as a series of nested objects/arrays:

```
{
	"school": 1,
	"student": [{
		"student": 1,
		"school_year": [{
			"school_year": 2015,
			"grade": [{
				"grade": 11,
				"test_type": "reading",
				"test_score": 275
			}, {
				"grade": 11,
				"test_type": "math",
				"test_score": 325
			}, {
				"grade": 11,
				"test_type": "sat",
				"test_score": 1950
			}]
		}, {
			"school_year": 2016,
			"grade": [{
				"grade": 12,
				"test_type": "sat",
				"test_score": 1975
			}]
		}]
	}, {
		"student": 2,
		"school_year": [{
			"school_year": 2014,
			"grade": [{
				"grade": 7,
				"test_type": "reading",
				"test_score": 200
			}, {
				"grade": 7,
				"test_type": "math",
				"test_score": 193
			}]
		}, {
			"school_year": 2015,
			"grade": [{
				"grade": 8,
				"test_type": "reading",
				"test_score": 215
			}, {
				"grade": 8,
				"test_type": "math",
				"test_score": 197
			}]
		}]
	}]
}
```

Although there is some inference that needs to take place to structure the data in this example as a two-dimensional array, it would be relatively easy to infer that child nodes inherit the parent data (e.g., lines 4-28 would all include a value of student = 1).  There are other cases where this gets more complex (e.g., the Google Directions API payloads), but the same rules could apply where the end result looks something like a "normalized" table.  From that point it should be relatively easy for an end user to manipulate the data structure into a format that would be more amenable to their analysis and would better integrate with the way that several analytic platforms manage/handle data.

**Comment by wbuchanan** [comment]
Definitely not the "prettiest" solution possible, but I've worked out something to [flatten all of the nodes without loosing any ancestry information](https://github.com/wbuchanan/StataJSON/blob/master/src/main/java/org/paces/Stata/Input/FlatJSON.java).  It's fairly limited right now (e.g., either dumps the payload into an n x 2 or 2 x m tabular structure), but still gets the job done and should make it fairly easy for other Stata users to work with JSON data a bit more easily:

```Stata
. // Read data directly from a URL
. jsonio kv, file("http://maps.googleapis.com/maps/api/directions/json?origin=1250+W+Broadway+Ave,+Minneapolis,+MN&destination=4+Yawkey+Way,+Boston,+MA&waypoint
> s=optimize:true|Chicago,IL|Lexington,KY|Providence,RI") 

. 
. // Describe the data set in memory
. desc

Contains data
  obs:         1,327                          
 vars:             2                          
 size:       368,762                          
-----------------------------------------------------------------
              storage   display    value
variable name   type    format     label      variable label
-----------------------------------------------------------------
key             str44   %44s                  
value           strL    %9s                   
-----------------------------------------------------------------
Sorted by: 
     Note: Dataset has changed since last saved.

. 
. // Show the number of elements retrieved from the request
. count
  1,327

. 
. // List some of the entries from the returned results
. li in 20/30, fast sep(0)

     +----------------------------------------------------------+
     |                                          key       value |
     |----------------------------------------------------------|
 20. |               /routes_1/bounds/northeast/lng   -71.030.. |
 21. |               /routes_1/bounds/southwest/lat   38.0067.. |
 22. |               /routes_1/bounds/southwest/lng   -93.296.. |
 23. |                         /routes_1/copyrights   Map dat.. |
 24. |               /routes_1/legs_1/distance/text      413 mi |
 25. |              /routes_1/legs_1/distance/value      664140 |
 26. |               /routes_1/legs_1/duration/text   6 hours.. |
 27. |              /routes_1/legs_1/duration/value       22846 |
 28. |                 /routes_1/legs_1/end_address   Chicago.. |
 29. |            /routes_1/legs_1/end_location/lat   41.8781.. |
 30. |            /routes_1/legs_1/end_location/lng   -87.629.. |
     +----------------------------------------------------------+
```

It might take a while, but I think I could figure out a relatively easy/consistent way to structure some of this into a more formal 2D tabular structure like : 

```
routes, legs, location, lat, lng, address
1, 1, "end", 41.8781, -87.629, "Chicago..."
```

**Comment by cowtowncoder** [comment]
@wbuchanan  Thank you for sharing this. Also; if you want, I don't mind keeping this open, even if there are no immediate plans. Anyone looking for new things may want to browse open issues. Your call, of course.

**Comment by wbuchanan** [comment]
@cowtowncoder I have no problem leaving it open.  Tested it with a payload of legislative data ~33k lines long a week or so ago and it parsed and loaded everything close to a second.  Definitely helpful for dumping the data into a format that can be manipulated a bit more easily in statistical software.
