### ISSUE TITLE
[Jackson-3] Proposal for Renaming Property entities for Naming Symmetry

### ISSUE THREAD

**Issue by JooHyukKim** [FasterXML/jackson-future-ideas#70]
### Proposal
I propose the following naming schema to provide a clear and consistent structure:

- **Writer** suffix for serialization classes
- **Reader** suffix for deserialization classes

```text
com.fasterxml.jackson.databind.BeanProperty (Interface)
├── com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase
│   ├── com.fasterxml.jackson.databind.ser.PropertyWriter
│   │   ├── com.fasterxml.jackson.databind.ser.BeanPropertyWriter
│   │   │   ├── com.fasterxml.jackson.databind.ser.impl.AttributePropertyWriter
│   │   │   ├── com.fasterxml.jackson.databind.ser.impl.FilteredBeanPropertyWriter
│   │   │   │   └── com.fasterxml.jackson.databind.ser.impl.FilteredBeanPropertyWriter.MultiView
│   │   │   ├── com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter
│   │   │   └── com.fasterxml.jackson.databind.ext.OptionalHandlerFactory.OptionalBeanPropertyWriter
│   │   └── com.fasterxml.jackson.databind.ser.VirtualBeanPropertyWriter
│   └── com.fasterxml.jackson.databind.introspect.VirtualAnnotatedMember
├── com.fasterxml.jackson.databind.deser. SettableBeanProperty  -------------> PropertyReader
│   ├── com.fasterxml.jackson.databind.deser.CreatorProperty ------------------> CreatorPropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.FieldProperty ---------------> FieldPropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.MethodProperty --------------> MethodPropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.SetterlessProperty ----------> SetterlessPropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty ----> ManagedReferencePropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty ---> ObjectIdReferencePropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty -------> ObjectIdValuePropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty -> MergingPropertyReader
│   ├── com.fasterxml.jackson.databind.deser.impl.InnerClassProperty ----------> InnerClassPropertyReader
│   └── com.fasterxml.jackson.databind.deser.PropertyReader.Delegating --------> PropertyReader.Delegating
|----── com.fasterxml.jackson.databind.deser.impl.ValueInjector
└── com.fasterxml.jackson.databind.ser.impl.MapProperty
```

### Benefits
- Improved consistency and symmetry in class names
- Easier understanding of the codebase

###  Note

We will talk along the way the classes that are not mentioned here, yet.

**Comment by cowtowncoder** [comment]
I like this idea. I think I'd like to get https://github.com/FasterXML/jackson-databind/pull/4396 merged before this, but we can proceed with renaming right after (technically it is not strictly necessary to order things this way but might be slightly less problem merging).

**Comment by JooHyukKim** [comment]
> I like this idea. I think I'd like to get [FasterXML/jackson-databind#4396](https://github.com/FasterXML/jackson-databind/pull/4396) merged before this, but we can proceed with renaming right afte

Sounds good to me ✅

**Comment by JooHyukKim** [comment]
Updated hierarchy tree 👍🏼

**Comment by JooHyukKim** [comment]
Figured bring up this issue again, since concrete works for 3.0 been rolling in.
Updated hierarchy tree 👍🏼

**Comment by cowtowncoder** [comment]
@JooHyukKim Could you extend description a bit to indicate specific renaming suggestion? I think you are suggesting changes to deserialization side, so `SettableBeanProperty` to... `BeanPropertyReader`? And leaving serialization side as-is, having `Writer` suffix (`BeanPropertyWriter`)? But want to make sure I understand specific suggestion(s).

**Comment by JooHyukKim** [comment]
@cowtowncoder Sorry for the fuss, I don't think we need to pursue this now 🤔

Initially I thought it would be sort of low-haning fruit with huge consistency benefit.
But the classes in scope do not form actually deserialization-serialization symmetry with one another.

**Comment by cowtowncoder** [comment]
@JooHyukKim yeah I was wondering about that -- Reader/Writer symmetry has benefits, but in this case things are bit tangled so was not 100% sure how to easily improve things. Thanks for the update: it's perfectly fine to suggest/try things, even if just to find they don't work out in the end.
