### ISSUE TITLE
ObjectMapper Support for Dynamically Including/Excluding Properties during Serialization

### ISSUE THREAD

**Issue by apjoseph** [FasterXML/jackson-future-ideas#8]
It is quickly becoming a standard REST API practice to allow the method caller to dynamically choose which properties they want included/excluded from the returned JSON using dot notation. Obviously, mixins and views are inadequate for this purpose. Ideally, Jackson object mappers would have simple methods to support this out of the box :

```
List<String> includes =  ImmutableList.of("property1","property2.subProperty","property3.*");
List<String> excludes =  ImmutableList.of("property3.subProperty");

objectMapper.writeValueAsStringWithSpecifiedFields(object,includes,excludes)
```

Or is this already possible via another strategy/module?

**Comment by cowtowncoder** [comment]
I think this would probably make most sense for `jackson-databind` (as it'd probably implemented there), and/or discussing on mailing lists.

I am not sure whether this would be practical in context of POJOs; but I assume it would mostly be used for tree model (`JsonNode`) anyway and not for typed objects. But if so, this could perhaps be a separate component that allows such filtering.

Thinking out aloud it could actually be something to implement using streaming filter: existing single-JsonPointer filter should provide a starting point for anyone wanting to pursue this idea. In fact you might be best off just getting equivalent of a bunch of JsonPointers (although need not be, dotted notation could be ok as well).

**Comment by cowtowncoder** [comment]
While I can see (and know, from experience) usefulness of various kinds of filtering, I don't think there is anything concrete enough here to work on, so closing.
