### ISSUE TITLE
support json object graphs

### ISSUE THREAD

**Issue by rpridemore** [FasterXML/jackson-future-ideas#9]
I'm working on a application that needs to parse a huge amount of json from salesforce.  One of the messages seems to be pretty much a dump of their entire data model.  This data is not strictly a tree, but an object graph such as:
`{
   A [{
      id: 1
   },{
      id: 2
   }],
   B {
      fk: 1
   }
}`

We are using the databind functionality to turn the data into java objects.  Given the simple json example above, if B.fk is a reference to an id in one of the objects in the A array, I was thinking that this would be an ideal use for JsonPath in a new annotation on the B pojo.  The issue is how to implement it.  I believe I read that jackson performs a depth-first search when parsing the json, but regardless of the order it seems like there will be cases where such a path will refer to a portion of the graph that has not yet been parsed.  That leads me to believe this needs to be some sort of post-processor.

I'm an experienced java developer and would be willing to take a stab at this, but I do not know where to start.  Any pointers?

**Comment by cowtowncoder** [comment]
I think this would have to be an add-on project that makes use of in-memory full-graph representation, and not something that would be easy to add to `jackson-databind`.
You are correct in that while jackson streaming exposes token strictly in document order, databind does resolve some out-of-order references by buffering, and late binding (of Object Ids to object instances). However, those use cases do not build full tree model, they only buffer subsets, or keep references to Objects that are possible to be referenced.

So, yes, post-processing seems like the way: first bind to a usable structure, possibly `JsonNode`.
It may also be true that `JsonPointer` could work as reference if (but only if) references are always resolved against root node. Alternative of relative references would not be supportable using `JsonPointer`.

**Comment by cowtowncoder** [comment]
Ok, I don't think there is any specific idea for new features here. For discussions mailing lists work better. Closing.
